### ISSUE TITLE
Publish to pypi

### ISSUE THREAD

**Issue by Wilhelmsson177** [Wilhelmsson177/tonie-api#4]
Hello @moritzj29,

is it possible to publish your module to pypi? Other possibility: If you give your okay, I would fork and publish the repository.

**Comment by moritzj29** [comment]
Hello @Wilhelmsson177,
thanks for your interest in the project! Unfortunately I have no experience with pypi and do not use this project at the moment… If you are ok with it, I can transfer the whole project to you? I‘m not a big fan of unmaintained forks (or in this case base repositories)^^ I‘m very happy that this project is still helpful for some people :)

**Comment by Wilhelmsson177** [comment]
Hey @moritzj29,
I am interested. It does not seem to complicated https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account.

The basic credits to you will always be part of the readme.

**Comment by moritzj29** [comment]
alright, transfer request has been sent!

**Comment by Wilhelmsson177** [comment]
First release has been published https://pypi.org/project/tonie-api/

**Comment by moritzj29** [comment]
awesome, thanks for polishing the code and the repository!
